"""Connecticut town -> county, from the Census 2020 Gazetteer (county subdivisions).

Connecticut's eight counties no longer have governments but are still how
addresses and property data are grouped (Zillow, assessors), so sales are
filed under them.
"""

CT_TOWN_COUNTY = {
    "Andover": "Tolland",
    "Ansonia": "New Haven",
    "Ashford": "Windham",
    "Avon": "Hartford",
    "Barkhamsted": "Litchfield",
    "Beacon Falls": "New Haven",
    "Berlin": "Hartford",
    "Bethany": "New Haven",
    "Bethel": "Fairfield",
    "Bethlehem": "Litchfield",
    "Bloomfield": "Hartford",
    "Bolton": "Tolland",
    "Bozrah": "New London",
    "Branford": "New Haven",
    "Bridgeport": "Fairfield",
    "Bridgewater": "Litchfield",
    "Bristol": "Hartford",
    "Brookfield": "Fairfield",
    "Brooklyn": "Windham",
    "Burlington": "Hartford",
    "Canaan": "Litchfield",
    "Canterbury": "Windham",
    "Canton": "Hartford",
    "Chaplin": "Windham",
    "Cheshire": "New Haven",
    "Chester": "Middlesex",
    "Clinton": "Middlesex",
    "Colchester": "New London",
    "Colebrook": "Litchfield",
    "Columbia": "Tolland",
    "Cornwall": "Litchfield",
    "Coventry": "Tolland",
    "Cromwell": "Middlesex",
    "Danbury": "Fairfield",
    "Darien": "Fairfield",
    "Deep River": "Middlesex",
    "Derby": "New Haven",
    "Durham": "Middlesex",
    "East Granby": "Hartford",
    "East Haddam": "Middlesex",
    "East Hampton": "Middlesex",
    "East Hartford": "Hartford",
    "East Haven": "New Haven",
    "East Lyme": "New London",
    "East Windsor": "Hartford",
    "Eastford": "Windham",
    "Easton": "Fairfield",
    "Ellington": "Tolland",
    "Enfield": "Hartford",
    "Essex": "Middlesex",
    "Fairfield": "Fairfield",
    "Farmington": "Hartford",
    "Franklin": "New London",
    "Glastonbury": "Hartford",
    "Goshen": "Litchfield",
    "Granby": "Hartford",
    "Greenwich": "Fairfield",
    "Griswold": "New London",
    "Groton": "New London",
    "Guilford": "New Haven",
    "Haddam": "Middlesex",
    "Hamden": "New Haven",
    "Hampton": "Windham",
    "Hartford": "Hartford",
    "Hartland": "Hartford",
    "Harwinton": "Litchfield",
    "Hebron": "Tolland",
    "Kent": "Litchfield",
    "Killingly": "Windham",
    "Killingworth": "Middlesex",
    "Lebanon": "New London",
    "Ledyard": "New London",
    "Lisbon": "New London",
    "Litchfield": "Litchfield",
    "Lyme": "New London",
    "Madison": "New Haven",
    "Manchester": "Hartford",
    "Mansfield": "Tolland",
    "Marlborough": "Hartford",
    "Meriden": "New Haven",
    "Middlebury": "New Haven",
    "Middlefield": "Middlesex",
    "Middletown": "Middlesex",
    "Milford": "New Haven",
    "Monroe": "Fairfield",
    "Montville": "New London",
    "Morris": "Litchfield",
    "Naugatuck": "New Haven",
    "New Britain": "Hartford",
    "New Canaan": "Fairfield",
    "New Fairfield": "Fairfield",
    "New Hartford": "Litchfield",
    "New Haven": "New Haven",
    "New London": "New London",
    "New Milford": "Litchfield",
    "Newington": "Hartford",
    "Newtown": "Fairfield",
    "Norfolk": "Litchfield",
    "North Branford": "New Haven",
    "North Canaan": "Litchfield",
    "North Haven": "New Haven",
    "North Stonington": "New London",
    "Norwalk": "Fairfield",
    "Norwich": "New London",
    "Old Lyme": "New London",
    "Old Saybrook": "Middlesex",
    "Orange": "New Haven",
    "Oxford": "New Haven",
    "Plainfield": "Windham",
    "Plainville": "Hartford",
    "Plymouth": "Litchfield",
    "Pomfret": "Windham",
    "Portland": "Middlesex",
    "Preston": "New London",
    "Prospect": "New Haven",
    "Putnam": "Windham",
    "Redding": "Fairfield",
    "Ridgefield": "Fairfield",
    "Rocky Hill": "Hartford",
    "Roxbury": "Litchfield",
    "Salem": "New London",
    "Salisbury": "Litchfield",
    "Scotland": "Windham",
    "Seymour": "New Haven",
    "Sharon": "Litchfield",
    "Shelton": "Fairfield",
    "Sherman": "Fairfield",
    "Simsbury": "Hartford",
    "Somers": "Tolland",
    "South Windsor": "Hartford",
    "Southbury": "New Haven",
    "Southington": "Hartford",
    "Sprague": "New London",
    "Stafford": "Tolland",
    "Stamford": "Fairfield",
    "Sterling": "Windham",
    "Stonington": "New London",
    "Stratford": "Fairfield",
    "Suffield": "Hartford",
    "Thomaston": "Litchfield",
    "Thompson": "Windham",
    "Tolland": "Tolland",
    "Torrington": "Litchfield",
    "Trumbull": "Fairfield",
    "Union": "Tolland",
    "Vernon": "Tolland",
    "Voluntown": "New London",
    "Wallingford": "New Haven",
    "Warren": "Litchfield",
    "Washington": "Litchfield",
    "Waterbury": "New Haven",
    "Waterford": "New London",
    "Watertown": "Litchfield",
    "West Hartford": "Hartford",
    "West Haven": "New Haven",
    "Westbrook": "Middlesex",
    "Weston": "Fairfield",
    "Westport": "Fairfield",
    "Wethersfield": "Hartford",
    "Willington": "Tolland",
    "Wilton": "Fairfield",
    "Winchester": "Litchfield",
    "Windham": "Windham",
    "Windsor": "Hartford",
    "Windsor Locks": "Hartford",
    "Wolcott": "New Haven",
    "Woodbridge": "New Haven",
    "Woodbury": "Litchfield",
    "Woodstock": "Windham",
}

# Villages and boroughs that notices name instead of the town they belong to.
CT_VILLAGE_COUNTY = {
    "Stafford Springs": "Tolland", "Terryville": "Litchfield", "Winsted": "Litchfield", "Pawcatuck": "New London",
    "Mystic": "New London", "Jewett City": "New London", "Uncasville": "New London", "Gales Ferry": "New London",
    "Niantic": "New London", "Moosup": "Windham", "Danielson": "Windham", "Unionville": "Hartford",
    "Northford": "New Haven", "Rockville": "Tolland", "Broad Brook": "Hartford", "Collinsville": "Hartford",
}


def county_for(place):
    name = (place or "").strip().title()
    return CT_TOWN_COUNTY.get(name) or CT_VILLAGE_COUNTY.get(name)
